orders/urls.py
from django.urls import path
from . import views

app_name = "orders"
urlpatterns = [
    path('new/', views.new, name="new"),
    path('show/', views.show, name="show"),
    path('create/', views.create, name="create"),
    path('success/', views.success, name="success"),
    path('<int:id>/create_review/', views.create_review, name="create_review"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name="main"),
    path('orders/', include('orders.urls')),
    path('accounts/', include('allauth.urls')),
]

orders/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Order(models.Model):
    objects = models.Manager()
    spicy = models.CharField(max_length=200)
    sidemenus = models.CharField(max_length=200, blank=True, null=True)
    toppings = models.CharField(max_length=200, blank=True, null=True)
    drink = models.CharField(max_length=200, blank=True, null=True)
    
    user = models.ForeignKey(User, on_delete = models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def sidemenus_as_list(self):
        return self.sidemenus.split(', ')
    
    def toppings_as_list(self):
        return self.toppings.split(', ')
    
    def reviews(self):
        return Review.objects.filter(order=self)
    
    
class Review(models.Model):
    objects = models.Manager()
    content = models.TextField()
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    order = models.ForeignKey(Order, on_delete = models.CASCADE)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.content

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.contrib.auth.models import User
import pdb

# Create your views here.
def new(request):
    return render(request, 'orders/new.html')

def create(request):
    currentuser = request.user
    
    if request.method == "POST":
        spicy = request.POST.get('spicy')
        
        sidemenu_var = request.POST.getlist('sidemenu')
        sidemenus=[]
        if '1' in sidemenu_var:
            sidemenus.append('주먹김밥')
        if '2' in sidemenu_var:
            sidemenus.append('계란찜')
            
        str_sidemenus = ', '.join(str(x) for x in sidemenus)
        
        topping_var = request.POST.getlist('topping')
        toppings=[]
        if '1' in topping_var:
            toppings.append('치즈')
        if '2' in topping_var:
            toppings.append('햄(7개)')
        if '3' in topping_var:
            toppings.append('계란(2알)')
        if '4' in topping_var:
            toppings.append('메추리알(5알)')
        if '5' in topping_var:
            toppings.append('떡추가')
        if '6' in topping_var:
            toppings.append('오뎅추가')
        if '7' in topping_var:
            toppings.append('순대(300g)')
        if '8' in topping_var:
            toppings.append('베이컨')
        if '9' in topping_var:
            toppings.append('튀김만두(4개)')
        if '10' in topping_var:
            toppings.append('김말이(3개)')
        if '11' in topping_var:
            toppings.append('야채튀김(1개)')
        if '12' in topping_var:
            toppings.append('순살치킨(5개)')
        if '13' in topping_var:
            toppings.append('치즈스틱(3개)')
        if '14' in topping_var:
            toppings.append('모듬튀김(야채튀김1개+김말이1개+만두2개)')
        if '15' in topping_var:
            toppings.append('우동사리')
        if '16' in topping_var:
            toppings.append('라면사리')
        if '17' in topping_var:
            toppings.append('당면사리')
        if '18' in topping_var:
            toppings.append('중국당면')
        
        str_toppings = ', '.join(str(y) for y in toppings)
        pdb.set_trace()
        
        drink = request.POST.get('drink')
        order = Order.objects.create(spicy=spicy, sidemenus=str_sidemenus, toppings=str_toppings, drink=drink, user=currentuser)
        
    return render(request, 'orders/success.html', {'order': order, 'sidemenus': sidemenus, 'toppings': toppings})


def show(request):
    currentuser = request.user
    orders = Order.objects.filter(user=currentuser).order_by('-id')
    # pdb.set_trace()
    return render(request, 'orders/show.html', {'orders': orders})
    
    
def success(request):
    return render(request, 'orders/success.html')
    

def create_review(request, id):
    order = get_object_or_404(Order, pk=id)
    
    if request.method == "POST":
        currentuser = request.user
        content = request.POST.get('content')
        review = Review(content=content, order=order, user=currentuser)
        review.save()
        
        return redirect('orders:show')

project/orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.contrib.auth.models import User
import pdb

# Create your views here.
def new(request):
    return render(request, 'orders/new.html')

def create(request):
    currentuser = request.user
    
    if request.method == "POST":
        spicy = request.POST.get('spicy')
        
        sidemenu_var = request.POST.getlist('sidemenu')
        sidemenus=[]
        if '1' in sidemenu_var:
            sidemenus.append('주먹김밥')
        if '2' in sidemenu_var:
            sidemenus.append('계란찜')
            
        str_sidemenus = ', '.join(str(x) for x in sidemenus)
        
        topping_var = request.POST.getlist('topping')
        toppings=[]
        if '1' in topping_var:
            toppings.append('치즈')
        if '2' in topping_var:
            toppings.append('햄(7개)')
        if '3' in topping_var:
            toppings.append('계란(2알)')
        if '4' in topping_var:
            toppings.append('메추리알(5알)')
        if '5' in topping_var:
            toppings.append('떡추가')
        if '6' in topping_var:
            toppings.append('오뎅추가')
        if '7' in topping_var:
            toppings.append('순대(300g)')
        if '8' in topping_var:
            toppings.append('베이컨')
        if '9' in topping_var:
            toppings.append('튀김만두(4개)')
        if '10' in topping_var:
            toppings.append('김말이(3개)')
        if '11' in topping_var:
            toppings.append('야채튀김(1개)')
        if '12' in topping_var:
            toppings.append('순살치킨(5개)')
        if '13' in topping_var:
            toppings.append('치즈스틱(3개)')
        if '14' in topping_var:
            toppings.append('모듬튀김(야채튀김1개+김말이1개+만두2개)')
        if '15' in topping_var:
            toppings.append('우동사리')
        if '16' in topping_var:
            toppings.append('라면사리')
        if '17' in topping_var:
            toppings.append('당면사리')
        if '18' in topping_var:
            toppings.append('중국당면')
        
        str_toppings = ', '.join(str(y) for y in toppings)
        
        drink = request.POST.get('drink')
        order = Order.objects.create(spicy=spicy, sidemenus=str_sidemenus, toppings=str_toppings, drink=drink, user=currentuser)
        
    return render(request, 'orders/success.html', {'order': order, 'sidemenus': sidemenus, 'toppings': toppings})


def show(request):
    currentuser = request.user
    orders = Order.objects.filter(user=currentuser).order_by('-id')
    # pdb.set_trace()
    return render(request, 'orders/show.html', {'orders': orders})
    
    
def success(request):
    return render(request, 'orders/success.html')
    

def create_review(request, id):
    order = get_object_or_404(Order, pk=id)
    
    if request.method == "POST":
        currentuser = request.user
        content = request.POST.get('content')
        review = Review(content=content, order=order, user=currentuser)
        review.save()
        
        return redirect('orders:show')

project/views.py
from django.shortcuts import render
# from orders .models import Order

def main(request):
    # orders = Post.objects.all()
    return render(request, 'main.html')

orders/templates/orders/new.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <h2 class="h-text">주문하기</h2>
    <h5 class="h-text">모든 엽기떡볶이에는 치즈+햄+단무지가 기본으로 제공됩니다.</h5>
    <br>
    <form action="{% url 'orders:create' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
			<label class="control-label">* 매운맛 조절</label>
			<div class="col-xs-2">
				<select class="custom-select" name="spicy">
					<option value="매운맛">매운맛</option>
					<option value="오리지널" selected>오리지널(엽떡기본)</option>
					<option value="덜매운맛">덜매운맛</option>
					<option value="엽떡초보맛">엽떡초보맛</option>
					<option value="착한맛">착한맛</option>
				</select>
			</div>
		</div>
		
		<br>
		
		<label>* 사이드 메뉴</label>
		<div class="container row">
    		<div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="sidemenu1" value="1" name="sidemenu">
                <label class="custom-control-label" for="sidemenu1">주먹김밥</label>
            </div>
            &nbsp; &nbsp;
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="sidemenu2" value="2" name="sidemenu">
                <label class="custom-control-label" for="sidemenu2">계란찜</label>
            </div>
        </div>
        
        <br>
        
        <label>* 토핑</label>
        {% include 'orders/topping.html' %}
		
		<br>
		
		<label>* 음료</label>
		<div class="container row">
    		<div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="drink" value="써핑쿨" name="drink">
                <label class="custom-control-label" for="drink">써핑쿨</label>
            </div>
        </div>
		
		<br>
		
        <input type="submit" class="btn btn-danger" value="주문하기">
    </form>
    <br><br>
{% endblock %}

orders/templates/orders/show.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <h2 class="h-text">{{ user.username }}님의 주문내역</h2>
    <br>
    
    <div class="row">
        {% for order in orders %}
        <div class="col-3">
            <div class="card">
              <div class="card-header text-center">
                주문번호 : {{ order.id }}
              </div>
              <div class="card-body text-center">
                <h5 class="card-title">엽기떡볶이 {{ order.spicy }}</h5>
                <p class="card-text">
                    {% for sidemenu in order.sidemenus_as_list %}
                        {{ sidemenu }}<br>
                    {% endfor %}
                    
                    {% for topping in order.toppings_as_list %}
                        {{ topping }}<br>
                    {% endfor %}
                    
                    {% if order.drink %}
                        {{ order.drink }}<br>
                    {% endif %}
                </p>
                <p class="text-muted">
                    {{ order.created_at }}
                </p>
              </div>
              <div class="card-footer">
                  
                
                * 리뷰 작성하기<br>
                <form action="{% url 'orders:create_review' order.id %}" method="POST">
                {% csrf_token %}
                    <div class="row">
                        <div class="col-8">
                            <input type="text" class="form-control" name="content">
                        </div>
                        <div class="col-4">
                            <input type="hidden" name="id" value="{{ order.id }}">
                            <input type="submit" class="btn btn-outline-danger" value="작성">
                        </div>
                    </div>
                </form>
                
                {% for review in order.reviews.all %}
                    {{ review.content }}<br>
                {% endfor %}
                
              </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <br><br>
    <button type="button" onclick="topFunction()" class="scrollBtn" id="myBtn">Top</button><br><br>
{% endblock %}

orders/templates/orders/success.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <h2 class="h-text">주문 완료</h2>
    <h5 class="h-text">{{ user.username }}님이 주문하신 내역은 다음과 같습니다.</h5>
    <br>
    
    <div class="col-3 order-text">
        <div class="card">
          <div class="card-header text-center">
            주문번호 : {{ order.id }}
          </div>
          <div class="card-body text-center">
            <h5 class="card-title">엽기떡볶이 {{ order.spicy }}</h5>
            <p class="card-text">
                {% if sidemenus %}
                    {% for item in sidemenus %}
                        {{ item }}<br>
                    {% endfor %}
                {% endif %}
                {% if toppings %}
                    {% for item in toppings %}
                        {{ item }}<br>
                    {% endfor %}
                {% endif %}
                {% if order.drink %}
                    {{ order.drink }}
                {% endif %}
            </p>
          </div>
        </div>
    </div>
    <br><br>
    <button type="button" onclick="topFunction()" class="scrollBtn" id="myBtn">Top</button><br><br>
{% endblock %}

orders/templates/orders/topping.html
<div class="container row bottom-margin-10">
	<div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="check1" value="1" name="topping">
        <label class="custom-control-label" for="check1">치즈</label>
    </div>
    &nbsp; &nbsp;
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="check2" value="2" name="topping">
        <label class="custom-control-label" for="check2">햄(7개)</label>
    </div>
    &nbsp; &nbsp;
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="check3" value="3" name="topping">
        <label class="custom-control-label" for="check3">계란(2알)</label>
    </div>
    &nbsp; &nbsp;
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="check4" value="4" name="topping">
        <label class="custom-control-label" for="check4">메추리알(5알)</label>
    </div>
    &nbsp; &nbsp;
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="check5" value="5" name="topping">
        <label class="custom-control-label" for="check5">떡추가</label>
    </div>
    &nbsp; &nbsp;
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="check6" value="6" name="topping">
        <label class="custom-control-label" for="check6">오뎅추가</label>
    </div>
    &nbsp; &nbsp;
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="check7" value="7" name="topping">
        <label class="custom-control-label" for="check7">순대(300g)</label>
    </div>
    &nbsp; &nbsp;
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="check8" value="8" name="topping">
        <label class="custom-control-label" for="check8">베이컨</label>
    </div>
</div>

<label>* 튀김</label>
<div class="container row bottom-margin-10">
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="check9" value="9" name="topping">
        <label class="custom-control-label" for="check9">튀김만두(4개)</label>
    </div>
    &nbsp; &nbsp;
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="check10" value="10" name="topping">
        <label class="custom-control-label" for="check10">김말이(3개)</label>
    </div>
    &nbsp; &nbsp;
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="check11" value="11" name="topping">
        <label class="custom-control-label" for="check11">야채튀김(1개)</label>
    </div>
    &nbsp; &nbsp;
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="check12" value="12" name="topping">
        <label class="custom-control-label" for="check12">순살치킨(5개)</label>
    </div>
    &nbsp; &nbsp;
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="check13" value="13" name="topping">
        <label class="custom-control-label" for="check13">치즈스틱(3개)</label>
    </div>
    &nbsp; &nbsp;
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="check14" value="14" name="topping">
        <label class="custom-control-label" for="check14">모듬튀김(야채튀김1개+김말이1개+만두2개)</label>
    </div>
</div>

<label>* 면</label>
<div class="container row">
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="check15" value="15" name="topping">
        <label class="custom-control-label" for="check15">우동사리</label>
    </div>
    &nbsp; &nbsp;
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="check16" value="16" name="topping">
        <label class="custom-control-label" for="check16">라면사리</label>
    </div>
    &nbsp; &nbsp;
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="check17" value="17" name="topping">
        <label class="custom-control-label" for="check17">당면사리</label>
    </div>
    &nbsp; &nbsp;
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="check18" value="18" name="topping">
        <label class="custom-control-label" for="check18">중국당면</label>
    </div>
    &nbsp; &nbsp;
</div>

templates/base.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
    
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    
    <!-- Javascirpt -->
    <script type="text/javascript" src="{% static 'js/project.js' %}"></script>
    
    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <title>엽기떡볶이</title>
  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light bottom-margin-30 h-text">
          <a class="navbar-brand" href="{% url 'main' %}">
            <img src="{% static 'images/fire.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            엽기떡볶이
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">

              {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'orders:new' %}">주문하기</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'orders:show' %}">주문내역</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                  </li>
              {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_login' %}">Sign In</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                  </li>
              {% endif %}
              
            </ul>
          </div>
        </nav>
      <div class="container order-text">
      {% block content %}
      
      {% endblock %}
      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/main.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="container row">
        <div class="col-5">
            <h1>매운맛 떡볶이의 원조<br>엽기떡볶이 !</h1>
            {% if user.is_authenticated %}
            {% else %}
            <h4>* 로그인/회원가입 후 주문해 주세요.</h4>
            <br>
            <a href="{% url 'account_login' %}" class="btn btn-outline-danger">로그인</a>&nbsp; &nbsp;
            <a href="{% url 'account_signup' %}" class="btn btn-outline-danger">회원가입</a>
            {% endif %}
        </div>
        <div class="col-7">
            <img src="{% static 'images/yupdduck.jpg' %}">
        </div>
    </div>
{% endblock %}